"""
Contains the drivetrain, built off CTRE's Swerve Project Generator.
"""
import ctypes
import math
from dataclasses import dataclass, field
from typing import Callable, overload, Self

from commands2 import Command, Subsystem
from commands2.sysid import SysIdRoutine
from pathplannerlib.auto import AutoBuilder
from pathplannerlib.config import RobotConfig, PIDConstants
from pathplannerlib.controller import PPHolonomicDriveController
from pathplannerlib.logging import PathPlannerLogging
from phoenix6 import SignalLogger, swerve, units, utils
from phoenix6.phoenix_native import (SwerveDriveState_t, SwerveModuleState_t,
                                     SwerveModulePosition_t, Native)
from phoenix6.swerve import SwerveModuleState
from phoenix6.swerve.requests import ApplyRobotSpeeds
from pykit.logger import Logger
from wpilib import DriverStation, Notifier, RobotController
from wpilib.sysid import SysIdRoutineLog
from wpimath.geometry import Pose2d, Rotation2d
from wpimath.kinematics import ChassisSpeeds
from wpiutil.wpistruct import make_wpistruct

# Robot config
from robot_config import currentRobot, Robot

if currentRobot == Robot.LARRY:
    from generated.larry.tuner_constants import TunerSwerveDrivetrain
else:
    from generated.tuner_constants import TunerSwerveDrivetrain


class SwerveSubsystem(Subsystem, swerve.SwerveDrivetrain):
    """
    Class that extends the Phoenix 6 SwerveDrivetrain class and implements
    Subsystem so it can easily be used in command-based projects.

    Generated by the 2026 Tuner X Swerve Project Generator
    https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve
    /index.html
    """

    @make_wpistruct(name="SwerveState")
    @dataclass(slots=True)
    class SwerveDriveState(swerve.SwerveDrivetrain.SwerveDriveState):
        """
        Optimized SwerveDriveState to prevent thread locks.
        WPIStruct for faster logging.
        """
        odom_freq: float = 0.0
        speeds: ChassisSpeeds = field(default_factory=ChassisSpeeds)
        pose: Pose2d = field(default_factory=Pose2d)

        def _update_from_native(self, state: SwerveDriveState_t) -> Self:
            self.odom_freq = 1 / state.odometryPeriod if (
                    state.odometryPeriod > 0) else 0.0
            self.pose = Pose2d(
                state.pose.x,
                state.pose.y,
                Rotation2d(state.pose.theta)
            )
            self.speeds = ChassisSpeeds(
                state.speeds.vx,
                state.speeds.vy,
                state.speeds.omega
            )

    _SIM_LOOP_PERIOD: units.second = 0.004  # 4 ms

    _BLUE_ALLIANCE_PERSPECTIVE_ROTATION = Rotation2d.fromDegrees(0)
    """Blue alliance sees forward as 0 degrees (toward red alliance wall)"""
    _RED_ALLIANCE_PERSPECTIVE_ROTATION = Rotation2d.fromDegrees(180)
    """Red alliance sees forward as 180 degrees (toward blue alliance wall)"""

    @overload
    def __init__(
        self,
        drivetrain_constants: swerve.SwerveDrivetrainConstants,
        modules: list[swerve.SwerveModuleConstants],
        /,
    ) -> None:
        ...

    @overload
    def __init__(
        self,
        drivetrain_constants: swerve.SwerveDrivetrainConstants,
        odometry_update_frequency: units.hertz,
        modules: list[swerve.SwerveModuleConstants],
        /,
    ) -> None:
        ...

    @overload
    def __init__(
        self,
        drivetrain_constants: swerve.SwerveDrivetrainConstants,
        odometry_update_frequency: units.hertz,
        odometry_standard_deviation: tuple[float, float, float],
        vision_standard_deviation: tuple[float, float, float],
        modules: list[swerve.SwerveModuleConstants],
        /,
    ) -> None:
        ...

    @overload
    def __init__(
        self,
        drivetrain_constants: swerve.SwerveDrivetrainConstants,
        arg0: None,
        arg1: None,
        arg2: None,
        arg3: None,
        /,
    ) -> None:
        ...

    def __init__(
        self,
        drivetrain_constants: swerve.SwerveDrivetrainConstants,
        arg0=None,
        arg1=None,
        arg2=None,
        arg3=None,
    ):
        Subsystem.__init__(self)
        TunerSwerveDrivetrain.__init__(
            self, drivetrain_constants, arg0, arg1, arg2, arg3
        )

        self._sim_notifier: Notifier | None = None
        self._last_sim_time: units.second = 0.0

        self._has_applied_operator_perspective = False

        # Swerve requests to apply during SysId characterization
        self._translation_characterization = (
            swerve.requests.SysIdSwerveTranslation())
        self._steer_characterization = swerve.requests.SysIdSwerveSteerGains()
        self._rotation_characterization = swerve.requests.SysIdSwerveRotation()

        self._sys_id_routine_translation = SysIdRoutine(
            SysIdRoutine.Config(
                # Use default ramp rate (1 V/s) and timeout (10 s)
                # Reduce dynamic voltage to 4 V to prevent brownout
                stepVoltage=4.0,
                # Log state with SignalLogger class
                recordState=lambda recordState: SignalLogger.write_string(
                    "SysIdTranslation_State",
                    SysIdRoutineLog.stateEnumToString(recordState)
                ) and None,
            ),
            SysIdRoutine.Mechanism(
                lambda output: self.set_control(
                    self._translation_characterization.with_volts(output)
                ),
                lambda log: None,
                self,
            ),
        )

        self._sys_id_routine_steer = SysIdRoutine(
            SysIdRoutine.Config(
                # Use default ramp rate (1 V/s) and timeout (10 s)
                # Use dynamic voltage of 7 V
                stepVoltage=7.0,
                # Log state with SignalLogger class
                recordState=lambda recordState: SignalLogger.write_string(
                    "SysIdSteer_State",
                    SysIdRoutineLog.stateEnumToString(recordState)
                ) and None,
            ),
            SysIdRoutine.Mechanism(
                lambda output: self.set_control(
                    self._steer_characterization.with_volts(output)
                ),
                lambda log: None,
                self,
            ),
        )

        self._sys_id_routine_rotation = SysIdRoutine(
            SysIdRoutine.Config(
                # This is in radians per second², but SysId only supports
                # "volts per second"
                rampRate=math.pi / 6,
                # Use dynamic voltage of 7 V
                stepVoltage=7.0,
                # Use default timeout (10 s)
                # Log state with SignalLogger class
                recordState=lambda recordState: SignalLogger.write_string(
                    "SysIdSteer_State",
                    SysIdRoutineLog.stateEnumToString(recordState)
                ) and None,
            ),
            SysIdRoutine.Mechanism(
                lambda output: (
                                   # output is actually radians per second,
                                   # but SysId only supports "volts"
                                   self.set_control(
                                       self._rotation_characterization.with_rotational_rate(
                                           output
                                       )
                                   ),
                                   # also log the requested output for SysId
                                   SignalLogger.write_double(
                                       "Rotational_Rate",
                                       output
                                   ),
                               )
                               and None,
                lambda log: None,
                self,
            ),
        )

        self._sys_id_routine_to_apply = self._sys_id_routine_translation
        """The SysId routine to test"""

        # Create config from GUI settings
        config = RobotConfig.fromGUISettings()
        self._apply_robot_speeds = ApplyRobotSpeeds()
        AutoBuilder.configure(
            # Supplier of current robot pose
            lambda: self.get_cached_state().pose,
            # Consumer for seeding pose against auto
            self.reset_pose,
            # Supplier of current robot speeds
            lambda: self.get_cached_state().speeds,
            # Consumer of ChassisSpeeds and feedforwards to drive the robot
            lambda speeds, feedforwards: self.set_control(
                self._apply_robot_speeds
                .with_speeds(speeds)
                .with_wheel_force_feedforwards_x(
                    feedforwards.robotRelativeForcesXNewtons
                )
                .with_wheel_force_feedforwards_y(
                    feedforwards.robotRelativeForcesYNewtons
                )
            ),
            PPHolonomicDriveController(
                PIDConstants(3, 0.0, 0.0),
                PIDConstants(3, 0.0, 0.0)
            ),
            config,
            lambda: DriverStation.getAlliance() == DriverStation.Alliance.kRed,
            self
        )

        # PathPlanner logging
        PathPlannerLogging.setLogTargetPoseCallback(lambda pose: Logger.recordOutput("PathPlanner/Target", pose))
        PathPlannerLogging.setLogActivePathCallback(lambda path: Logger.recordOutput("PathPlanner/Path", path))

        # State optimizations
        n = len(self.modules)
        self._swerve_state = self.SwerveDriveState()
        self._module_states = [SwerveModuleState() for _ in
                               range(n)]
        self._module_targets = [SwerveModuleState() for _ in
                                range(n)]

        # C structs
        self._c_module_states = (SwerveModuleState_t * n)()
        self._c_module_targets = (SwerveModuleState_t * n)()
        self._c_module_positions = (SwerveModulePosition_t * n)()
        self._c_state = SwerveDriveState_t()
        self._c_state.moduleStates = self._c_module_states
        self._c_state.moduleTargets = self._c_module_targets
        self._c_state.modulePositions = self._c_module_positions

        if utils.is_simulation():
            self._start_sim_thread()

    def apply_request(
        self, request: Callable[[], swerve.requests.SwerveRequest]
    ) -> Command:
        """
        Returns a command that applies the specified control request to this
        swerve drivetrain.
        """
        return self.run(lambda: self.set_control(request()))

    def sys_id_quasistatic(self, direction: SysIdRoutine.Direction) -> Command:
        """
        Runs the SysId Quasistatic test in the given direction for the routine
        specified by self.sys_id_routine_to_apply.
        """
        return self._sys_id_routine_to_apply.quasistatic(direction)

    def sys_id_dynamic(self, direction: SysIdRoutine.Direction) -> Command:
        """
        Runs the SysId Dynamic test in the given direction for the routine
        specified by self.sys_id_routine_to_apply.
        """
        return self._sys_id_routine_to_apply.dynamic(direction)

    def get_cached_state(self) -> SwerveDriveState:
        """
        Returns the current state of the drivetrain.
        Subsystems needing the state should use this to prevent GIL.
        """
        return self._swerve_state

    def periodic(self):
        # Periodically try to apply the operator perspective.
        # If we haven't applied the operator perspective before,
        #   then we should apply it regardless of DS state.
        # This allows us to correct the perspective in case the robot code
        # restarts
        #   mid-match.
        # Otherwise, only check and apply the operator perspective if the DS
        # is disabled.
        # This ensures driving behavior doesn't change
        #   until an explicit disable event occurs during testing.
        if (not self._has_applied_operator_perspective or
                DriverStation.isDisabled()):
            alliance_color = DriverStation.getAlliance()
            if alliance_color is not None:
                self.set_operator_perspective_forward(
                    self._RED_ALLIANCE_PERSPECTIVE_ROTATION
                    if alliance_color == DriverStation.Alliance.kRed
                    else self._BLUE_ALLIANCE_PERSPECTIVE_ROTATION
                )
                self._has_applied_operator_perspective = True

        # Update current state
        module_states = self._module_states
        module_targets = self._module_targets
        c_states = self._c_module_states
        c_targets = self._c_module_targets
        Native.api_instance().c_ctre_phoenix6_swerve_drivetrain_get_state(
            self._drivetrain_id, ctypes.byref(self._c_state)
        )
        self._swerve_state._update_from_native(self._c_state)
        Logger.recordOutput("Drive/State", self._swerve_state)

        # Mutate pre-allocated lists, no allocation
        for ms, mt, cs, ct in zip(
                module_states,
                module_targets,
                c_states,
                c_targets
        ):
            ms.speed = cs.speed
            ms.angle = Rotation2d(cs.angle)
            mt.speed = ct.speed
            mt.angle = Rotation2d(ct.angle)

        Logger.recordOutput("Drive/Modules/States", module_states)
        Logger.recordOutput("Drive/Modules/Targets", module_targets)

    def _start_sim_thread(self):
        def _sim_periodic():
            current_time = utils.get_current_time_seconds()
            delta_time = current_time - self._last_sim_time
            self._last_sim_time = current_time

            # use the measured time delta, get battery voltage from WPILib
            self.update_sim_state(
                delta_time,
                RobotController.getBatteryVoltage()
            )

        # Run simulation at a faster rate so PID gains behave more reasonably
        self._last_sim_time = utils.get_current_time_seconds()
        self._sim_notifier = Notifier(_sim_periodic)
        self._sim_notifier.startPeriodic(self._SIM_LOOP_PERIOD)

    def add_vision_measurement(
        self,
        vision_robot_pose: Pose2d,
        timestamp: units.second,
        vision_measurement_std_devs: tuple[float, float, float] | None = None,
    ):
        """
        Adds a vision measurement to the Kalman Filter. This will correct the
        odometry pose estimate while still accounting for measurement noise.

        Note that the vision measurement standard deviations passed into
        this method
        will continue to apply to future measurements until a subsequent
        call to
        set_vision_measurement_std_devs or this method.
        """
        TunerSwerveDrivetrain.add_vision_measurement(
            self,
            vision_robot_pose,
            utils.fpga_to_current_time(timestamp),
            vision_measurement_std_devs
        )

    def sample_pose_at(self, timestamp: units.second) -> Pose2d | None:
        """
        Return the pose at a given timestamp, if the buffer is not empty.

        :param timestamp: The timestamp of the pose in seconds.
        :type timestamp: second
        :returns: The pose at the given timestamp (or None if the buffer is
        empty).
        :rtype: Pose2d | None
        """
        return TunerSwerveDrivetrain.sample_pose_at(
            self,
            utils.fpga_to_current_time(timestamp)
        )
